language: python
python:
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jackmeix
  password:
    secure: fSSQ/cP1qX+Cu/+KKcOvKfRW4UjaLRfanZW0Mj3YVZKfmS1uEnFUPZLP5XvHhQOCm/pft9YUqMlUI2V/YJAuOM6xjHiD43oon0mh6M2O+yPpkVTE5RS0j9sqlyYCFu++6/MlEY9RV502lG0ZWoO4Mo/AJa87IpmV9S9SlnS0/gO2oer7r7pVpgBqcGcoORMKVg5Yqth51J+7cyJj3fpgLtnFfC11hDNtvfge+5ZgScfwmYWnb5ScNBVE2CvM5ZdV7bDEgOCLPqHqJFzpEHhMoJxfb0Z75N8N/CN5K8CvL3XVKaVq4SKIO+gcP5Q2fYv20R6qr4Osybxg/kStGbiejuqp5TWWTFftkif6brD53Jhmkcg4XFG4ACX20ztG08YTV9smyXIgNv5DsavGuxbTOPj9VP3fM32ou+DKi/RaMRYGFBwI9Xk7zDTA292Jew0B7z5NYITNiu7f+v0I5p/KA4wBLfnbfGzeRppJUp1YUiaFCKy0RjKcZFGg+2yvQ25j5RAbUTMn53GiQ4X65S+arOa596B6fO7KqlM0c/Q7UO6EKtQY78UzltMREAQtrTYir8YNk4s+pkznsIENFrfdeNFyRgMlFs8ZPc0RrJmU5zN5apX9r8bGjIq6EOWNIfH3/BYvxzBwC57I8AMZmrnlxe8WsHMXNJoM7sHPLMQQnNU=
  on:
    tags: true
    repo: jmeixensperger/meix
    python: 2.7
